<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.mycompany</groupId>
		<artifactId>parent-pom</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>com/mycompany/parent-pom/1.0.0-SNAPSHOT/parent-pom-1.0.0-SNAPSHOT.pom
		</relativePath>
	</parent>
	<groupId>com.mycompany</groupId>
	<artifactId>emrdsf-eu-s-einvoicing-esker</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>mule-application</packaging>

	<name>emrdsf-eu-s-einvoicing-esker</name>

	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-objectstore-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.emerson.asl.cle</groupId>
			<artifactId>emersoncle</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<version>1.2.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>central</id>
			<name>emrsonmule</name>
			<url>http://usstlaspeaiap0c.emrsn.org:8081/repository/EmersonMuleSoft/
			</url>
			<layout>default</layout>
		</repository>
	</repositories>
	<distributionManagement>
		<repository>
			<id>anypoint-exchange</id>
			<name>Exchange Repository</name>
			<url>https://maven.anypoint.mulesoft.com/api/v1/organizations/b848b0fb-23f3-4c1e-9541-561ee816b942/maven
			</url>
			<layout>default</layout>
		</repository>
	</distributionManagement>
</project>
